services:

  banking-ai:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      APP_NAME: Banking AI
      APP_VERSION: 0.1.0

      OLLAMA_HOST: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3.2

    extra_hosts:
      - "host.docker.internal:host-gateway"